// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Feed.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Book;
@class Sale;
@class SaleImage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FeedRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FeedRoot : GPBRootObject
@end

#pragma mark - Book

typedef GPB_ENUM(Book_FieldNumber) {
  Book_FieldNumber_Id_p = 1,
  Book_FieldNumber_FullTitle = 2,
  Book_FieldNumber_Link = 3,
  Book_FieldNumber_UniformTitle = 4,
  Book_FieldNumber_Ean13 = 5,
};

@interface Book : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fullTitle;
/** Test to see if @c fullTitle has been set. */
@property(nonatomic, readwrite) BOOL hasFullTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *link;
/** Test to see if @c link has been set. */
@property(nonatomic, readwrite) BOOL hasLink;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uniformTitle;
/** Test to see if @c uniformTitle has been set. */
@property(nonatomic, readwrite) BOOL hasUniformTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ean13;
/** Test to see if @c ean13 has been set. */
@property(nonatomic, readwrite) BOOL hasEan13;

@end

#pragma mark - SaleImage

typedef GPB_ENUM(SaleImage_FieldNumber) {
  SaleImage_FieldNumber_SaleId = 1,
  SaleImage_FieldNumber_ImgType = 2,
  SaleImage_FieldNumber_ImageName = 3,
  SaleImage_FieldNumber_CreatedAt = 4,
};

@interface SaleImage : GPBMessage

@property(nonatomic, readwrite) int64_t saleId;

@property(nonatomic, readwrite) BOOL hasSaleId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgType;
/** Test to see if @c imgType has been set. */
@property(nonatomic, readwrite) BOOL hasImgType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imageName;
/** Test to see if @c imageName has been set. */
@property(nonatomic, readwrite) BOOL hasImageName;

@property(nonatomic, readwrite) int32_t createdAt;

@property(nonatomic, readwrite) BOOL hasCreatedAt;
@end

#pragma mark - Sale

typedef GPB_ENUM(Sale_FieldNumber) {
  Sale_FieldNumber_Id_p = 1,
  Sale_FieldNumber_SellerId = 2,
  Sale_FieldNumber_SellerUsername = 3,
  Sale_FieldNumber_Book = 4,
  Sale_FieldNumber_Desription = 5,
  Sale_FieldNumber_Price = 6,
  Sale_FieldNumber_Location = 7,
  Sale_FieldNumber_Latitude = 8,
  Sale_FieldNumber_Longitude = 9,
  Sale_FieldNumber_Sold = 10,
  Sale_FieldNumber_Categories = 11,
  Sale_FieldNumber_CreatedAt = 12,
  Sale_FieldNumber_ExtraInfo = 13,
  Sale_FieldNumber_ImagesArray = 14,
};

@interface Sale : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *sellerId;
/** Test to see if @c sellerId has been set. */
@property(nonatomic, readwrite) BOOL hasSellerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sellerUsername;
/** Test to see if @c sellerUsername has been set. */
@property(nonatomic, readwrite) BOOL hasSellerUsername;

@property(nonatomic, readwrite, strong, null_resettable) Book *book;
/** Test to see if @c book has been set. */
@property(nonatomic, readwrite) BOOL hasBook;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desription;
/** Test to see if @c desription has been set. */
@property(nonatomic, readwrite) BOOL hasDesription;

@property(nonatomic, readwrite, copy, null_resettable) NSString *price;
/** Test to see if @c price has been set. */
@property(nonatomic, readwrite) BOOL hasPrice;

@property(nonatomic, readwrite, copy, null_resettable) NSString *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) BOOL hasLatitude;
@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite) BOOL hasLongitude;
@property(nonatomic, readwrite) BOOL sold;

@property(nonatomic, readwrite) BOOL hasSold;
@property(nonatomic, readwrite, copy, null_resettable) NSString *categories;
/** Test to see if @c categories has been set. */
@property(nonatomic, readwrite) BOOL hasCategories;

@property(nonatomic, readwrite) int32_t createdAt;

@property(nonatomic, readwrite) BOOL hasCreatedAt;
@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo;
/** Test to see if @c extraInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtraInfo;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SaleImage*> *imagesArray;
/** The number of items in @c imagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@end

#pragma mark - Feed

typedef GPB_ENUM(Feed_FieldNumber) {
  Feed_FieldNumber_SalesArray = 1,
};

@interface Feed : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Sale*> *salesArray;
/** The number of items in @c salesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger salesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
